### ISSUE TITLE
mismatched checksums

### ISSUE THREAD

**Issue by natemann** [workaroundgmbh/pg-connect-sdk-ios#11]
I am getting the following error when trying to download the package 

checksum of downloaded artifact of binary target 'ConnectSDK' (2c3b54755ebed641caacee06e750e44dd9f4a76794f11f208fe1a66600128c9d) does not match checksum specified by the manifest (1233e55c2efad431c5ffa74b5c1d773e5e31f824669e9c180bfa7709f6fef646)

**Comment by vlasty-proglove** [comment]
@natemann I think that was a problem with a specific branch that had a wrong checksum, the latest version does not have that problem.

If you are still facing this problem, resetting the package hash and clearing the project might do the trick.

But please check the latest version and let me know if you are still facing this problem.

**Comment by natemann** [comment]
Some of us are still experiencing this issue with version 2.2.0

**Comment by chris-jarvi** [comment]
The checksum listed in your `Package.swift` doesn't match the checksum of the zip file specified in the URL listed (also in your `Package.swift`).  When I download the file from that URL, it produces a checksum of "5097719bb7e3a98009e306b3dd4c12af80518acfbd9da1a5d4e37a06629e6f83"

**Comment by vlasty-proglove** [comment]
Yes, thank you @chris-jarvi , I just checked and it seems that the wrong checksum was set.
I just added the correct checksum, please reset your package cache and try again.

**Comment by chris-jarvi** [comment]
@vlasty-proglove thanks, it works now
